apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NODE_ENV

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT

            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_URL

            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: FRONTEND_URL

            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: JWT_EXPIRES_IN

            - name: JWT_COOKIE_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: JWT_COOKIE_EXPIRES_IN

            - name: EMAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: EMAIL_HOST

            - name: EMAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: EMAIL_PORT

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET

            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: EMAIL_USERNAME

            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: EMAIL_PASSWORD