apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: "production"
  PORT: "8000"
  DB_URL: "mongodb://mongodb:27017/onspot"
  FRONTEND_URL: "http://localhost:3000"
  JWT_EXPIRES_IN: "90d"
  JWT_COOKIE_EXPIRES_IN: "90"
  EMAIL_HOST: "sandbox.smtp.mailtrap.io"
  EMAIL_PORT: "2525"