apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  JWT_SECRET: YmY5ZDQxMjkzNzkxMzJmM2JkNGE0MjVhOTE3ODE2Yzc2MDUyODEzZWE5MGJlZDkzNDFhOGMzZTVlZGY3Mjlm
  EMAIL_USERNAME: NTFkZDc1M2RiYTA0MmI=
  EMAIL_PASSWORD: ZDg3NzYyNmM0Y2E0OWY=